# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d311f286ee9c8367d4a9b6c14785c139a280223646c81a779c3b0cd2bbecf23cf921222f57802dd5714eb59f0e9689f22c97995d36879272d8071d539674413

test:
  secret_key_base: 9330749bc2fcdde7bd646b729e903133778dca58ef479db2c7083264a9e9cc918d371d26bb7c8dd354c03e1ab63967e851c55131f0d54aeca771ae6945904062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
